### ISSUE TITLE
Triage s3tests

### ISSUE THREAD

**Issue by ad-m** [jamhall/s3rver#648]
Integration with s3tests tests is introduced in #647 for #640. A number of tests are not passed. We need to perform triage of tests that did not complete correctly (assess whether the error is due to incomplete implementation of the API or incorrect implementation and create appropriate separate issues).

- [ ] ERROR: test suite for <module 's3tests.functional' from '/opt/s3tests/s3tests/functional/__init__.py'>
- [ ] ERROR: s3tests_boto3.functional.test_headers.test_object_create_bad_expect_mismatch
- [ ] ERROR: s3tests_boto3.functional.test_headers.test_object_create_bad_expect_empty
- [ ] ERROR: s3tests_boto3.functional.test_headers.test_object_create_bad_contentlength_mismatch_above
- [ ] ERROR: s3tests_boto3.functional.test_headers.test_object_acl_create_contentlength_none
- [ ] ERROR: s3tests_boto3.functional.test_headers.test_bucket_create_bad_expect_mismatch
- [ ] ERROR: s3tests_boto3.functional.test_headers.test_bucket_create_bad_expect_empty
- [ ] ERROR: s3tests_boto3.functional.test_headers.test_object_create_bad_ua_empty_aws2
- [ ] ERROR: s3tests_boto3.functional.test_headers.test_object_create_bad_ua_none_aws2
- [ ] ERROR: s3tests_boto3.functional.test_headers.test_bucket_create_bad_ua_empty_aws2
- [ ] ERROR: s3tests_boto3.functional.test_headers.test_bucket_create_bad_ua_none_aws2
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_listv2_continuationtoken_empty
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_listv2_both_continuationtoken_startafter
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_list_return_data_versioning - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_list_objects_anonymous
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_listv2_objects_anonymous
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_requestid_matches_header_on_error
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_set_get_unicode_metadata
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_head_extended
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_create_naming_bad_short_empty
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_create_naming_bad_long
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_create_naming_bad_punctuation
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_create_exists
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_default
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_canned_during_create
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_canned
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_canned_publicreadwrite
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_canned_authenticatedread
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_acl_canned_bucketownerread
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_acl_canned_bucketownerfullcontrol
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_acl_full_control_verify_owner
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_acl_full_control_verify_attributes
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_canned_private_to_private
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_acl
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_acl_write
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_acl_writeacp
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_acl_read
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_acl_readacp
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_grant_userid_fullcontrol
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_grant_userid_read
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_grant_userid_readacp
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_grant_userid_write
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_grant_userid_writeacp
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_grant_nonexist_user
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_no_grants
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_header_acl_grants
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_grant_email
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_grant_email_not_exist
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_acl_revoke_all
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_logging_toggle
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_access_bucket_private_object_private
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_access_bucket_private_objectv2_private
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_access_bucket_private_object_publicread
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_access_bucket_private_objectv2_publicread
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_access_bucket_private_object_publicreadwrite
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_access_bucket_private_objectv2_publicreadwrite
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_access_bucket_publicread_object_private
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_access_bucket_publicread_object_publicread
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_access_bucket_publicread_object_publicreadwrite
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_access_bucket_publicreadwrite_object_private
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_access_bucket_publicreadwrite_object_publicread
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_access_bucket_publicreadwrite_object_publicreadwrite
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_create_naming_good_starts_alpha
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_create_naming_good_starts_digit
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_recreate_not_overriding
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_copy_not_owned_object_bucket
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_copy_versioned_bucket - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_copy_versioned_url_encoding - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_copy_versioning_multipart_upload - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_multipart_copy_small
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_multipart_copy_without_range
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_multipart_copy_special_names
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_multipart_copy_versioned - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_multipart_copy_multiple_sizes
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_abort_multipart_upload
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_list_multipart_upload
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_multipart_upload_missing_part
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_atomic_write_1mb
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_atomic_write_4mb
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_atomic_write_8mb
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_atomic_conditional_write_1mb
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_atomic_multipart_upload_write
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_bucket_create_suspend - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_obj_create_read_remove - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_obj_create_read_remove_head - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_obj_plain_null_version_removal - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_obj_plain_null_version_overwrite - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_obj_plain_null_version_overwrite_suspended - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_obj_suspend_versions - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_obj_create_versions_remove_all - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_obj_create_versions_remove_special_names - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_obj_create_overwrite_multipart - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_obj_list_marker - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_copy_obj_version - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_multi_object_delete - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_multi_object_delete_with_marker - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_multi_object_delete_with_marker_create - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioned_object_acl - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioned_object_acl_no_version_specified - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioned_concurrent_object_create_concurrent_remove - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioned_concurrent_object_create_and_remove - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_set
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_get
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_get_no_id
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_expiration
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecyclev2_expiration
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_expiration_versioning_enabled
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_set_date
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_expiration_date
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_expiration_days0
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_expiration_header_put
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_expiration_header_head
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_set_noncurrent
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_noncur_expiration
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_set_deletemarker
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_set_filter
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_set_empty_filter
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_deletemarker_expiration
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_set_multipart
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_lifecycle_multipart_expiration
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_sse_kms_method_head
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucketv2_policy
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_acl
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucketv2_policy_acl
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_different_tenant
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucketv2_policy_different_tenant
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_another_bucket
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucketv2_policy_another_bucket
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_set_condition_operator_end_with_IfExists
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_get_obj_head_tagging
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_put_delete_tags
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_get_tags_acl_public
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_put_tags_acl_public
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_delete_tags_obj_public
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_bucket_atomic_upload_return_version_id - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_versioning_bucket_multipart_upload_return_version_id - #7
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_get_obj_existing_tag
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_get_obj_tagging_existing_tag
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_put_obj_tagging_existing_tag
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_put_obj_copy_source
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_put_obj_copy_source_meta
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_put_obj_acl
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_put_obj_grant
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_put_obj_enc
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_put_obj_request_obj_tag
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_bucket_policy_get_obj_acl_existing_tag
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_lock
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_get_obj_lock
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_retention
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_get_obj_retention
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_retention_versionid
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_retention_override_default_retention
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_retention_increase_period
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_retention_shorten_period
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_retention_shorten_period_bypass
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_delete_object_with_retention
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_put_legal_hold
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_get_legal_hold
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_delete_object_with_legal_hold_on
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_delete_object_with_legal_hold_off
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_get_obj_metadata
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_object_lock_uploading_obj
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_user_policy
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_get_bucket_policy_status
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_get_public_acl_bucket_policy_status
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_get_authpublic_acl_bucket_policy_status
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_get_publicpolicy_acl_bucket_policy_status
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_get_nonpublicpolicy_acl_bucket_policy_status
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_get_nonpublicpolicy_deny_bucket_policy_status
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_get_default_public_block
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_put_public_block
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_block_public_put_bucket_acls
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_block_public_object_canned_acls
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_block_public_policy
- [ ] ERROR: s3tests_boto3.functional.test_s3.test_ignore_public_acls
- [ ] ERROR: test suite for <module 's3tests_boto3.functional' from '/opt/s3tests/s3tests_boto3/functional/__init__.py'>
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_md5_invalid_short
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_md5_bad
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_md5_empty
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_contentlength_none
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_authorization_empty
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_authorization_none
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_bucket_put_bad_canned_acl
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_bucket_create_bad_authorization_empty
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_bucket_create_bad_authorization_none
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_md5_invalid_garbage_aws2
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_contentlength_mismatch_below_aws2
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_authorization_incorrect_aws2
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_authorization_invalid_aws2
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_date_empty_aws2
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_date_none_aws2
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_object_create_bad_date_before_epoch_aws2
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_bucket_create_bad_authorization_invalid_aws2
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_bucket_create_bad_date_empty_aws2
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_bucket_create_bad_date_none_aws2
- [ ] FAIL: s3tests_boto3.functional.test_headers.test_bucket_create_bad_date_before_epoch_aws2
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_encoding_basic
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_list_encoding_basic
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_list_delimiter_prefix
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_delimiter_prefix
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_list_delimiter_prefix_underscore
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_delimiter_prefix_underscore
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_list_delimiter_not_skip_special
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_list_unordered
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_unordered
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_list_objects_anonymous_fail
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_listv2_objects_anonymous_fail
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_concurrent_set_canned_acl
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_anonymous_request
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_authenticated_request
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_authenticated_no_content_type
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_authenticated_request_bad_access_key
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_set_success_code
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_set_invalid_success_code
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_upload_larger_than_chunk
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_set_key_from_filename
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_ignored_header
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_case_insensitive_condition_fields
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_escaped_field_values
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_success_redirect_action
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_invalid_signature
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_invalid_access_key
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_missing_policy_condition
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_user_specified_header
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_request_missing_policy_specified_field
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_expired_policy
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_invalid_request_field_value
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_get_object_ifmatch_failed
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_get_object_ifunmodifiedsince_good
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_put_object_ifmatch_failed
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_put_object_ifmatch_nonexisted_failed
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_put_object_ifnonmatch_failed
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_put_object_ifnonmatch_overwrite_existed_failed
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_raw_get_object_acl
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_raw_get_x_amz_expires_out_max_range
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_anon_put
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_create_naming_bad_ip
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_create_naming_dns_underscore
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_create_naming_dns_dash_at_end
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_create_naming_dns_dot_dash
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_create_naming_dns_dash_dot
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_get_location
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_acl_default
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_acl_canned_during_create
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_acl_canned
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_acl_canned_publicreadwrite
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_acl_canned_authenticatedread
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_header_acl_grants
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_list_buckets_anonymous
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_list_buckets_bad_auth
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_bucket_create_special_key_names
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_copy_not_owned_bucket
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_multipart_copy_invalid_range
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_multipart_copy_improper_range
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_multipart_upload_size_too_small
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_abort_multipart_upload_not_found
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_multipart_upload_incorrect_etag
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_100_continue
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_cors_origin_response
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_cors_origin_wildcard
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_set_tagging
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_atomic_dual_write_1mb
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_atomic_dual_write_4mb
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_atomic_dual_write_8mb
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_atomic_dual_conditional_write_1mb
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_multipart_resend_first_finishes_last
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_ranged_request_return_trailing_bytes_response_code
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_lifecycle_id_too_long
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_lifecycle_same_id
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_lifecycle_invalid_status
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_lifecycle_set_invalid_date
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_encryption_sse_c_method_head
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_encryption_sse_c_present
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_encryption_sse_c_other_key
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_encryption_sse_c_invalid_md5
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_encryption_sse_c_no_md5
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_encryption_sse_c_no_key
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_encryption_key_no_sse_c
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_encryption_sse_c_multipart_invalid_chunks_1
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_encryption_sse_c_multipart_invalid_chunks_2
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_encryption_sse_c_multipart_bad_download
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_encryption_sse_c_post_object_authenticated_request
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_sse_kms_no_key
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_sse_kms_not_declared
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_sse_kms_post_object_authenticated_request
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_sse_kms_read_declare
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_put_excess_tags
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_put_excess_key_tags
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_put_excess_val_tags
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_tags_anonymous_request
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_post_object_tags_authenticated_request
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_put_obj_with_tags
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_lock_invalid_bucket
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_lock_with_days_and_years
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_lock_invalid_days
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_lock_invalid_years
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_lock_invalid_status
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_suspend_versioning
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_get_obj_lock_invalid_bucket
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_retention_invalid_bucket
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_put_obj_retention_invalid_mode
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_get_obj_retention_invalid_bucket
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_put_legal_hold_invalid_bucket
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_put_legal_hold_invalid_status
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_lock_get_legal_hold_invalid_bucket
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_copy_object_ifmatch_failed
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_copy_object_ifnonematch_good
- [ ] FAIL: s3tests_boto3.functional.test_s3.test_object_read_unreadable

Error logs used to generate list: https://gist.github.com/ad-m/5145f581f8deeafad4f0d43326d8660a

I open this issue with the assumption that contributors can edit the first comment in an issue. I am asking for a signal, if it is different, we will look for a better place to manage the list.
